### ISSUE TITLE
Need help for 'Index Error'

### ISSUE THREAD

**Issue by Orangecat2022** [a127000555/chunithm_crawler#1]
Hi there, I met a problem when running the code,  could you teach me how to fix it, please? Just wanna say sorry in advance if I post this in the wrong place, I didn't find out where is the 'review' button.

I'm a total rookie in programming. It took me a long time to install the pandas and requests. However, I really don't know if I installed them successfully since I did another research about 'Pip' and 'SSL'. That's really confusing.

I was using JupyterLab to run the code. After entering the cookies to log in, it appeared several rows of Update as shown in the attached photo. I'm not sure what is the problem. Did I miss anything required like Pandas or Requests etc? 

Thanks for the help!

![12](https://user-images.githubusercontent.com/99257373/152980735-b4312c9c-b271-4d79-95c1-d87a97ce62ec.png)

**Comment by a127000555** [comment]
Due to version update (Chunithm Stars -> Chunithm New), I'll update my code. You can just wait for few days and welcome to let me know your questions after updates.
